server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
    cloud:
      gateway:
        routes:
          - id: employee-service
            uri: http://localhost:8089
            predicates:
              - Path=/employee/**
          - id: department-service
            uri: http://localhost:8088
            predicates:
              - Path=/department/**
